from aiogram.fsm.state import State, StatesGroup


class GenerationStates(StatesGroup):
    choosing_mode = State()
    waiting_for_topic = State()
    waiting_for_goal = State()
    waiting_for_style = State()
    waiting_for_length = State()
    waiting_for_options = State()
    waiting_for_rewrite_text = State()
    waiting_for_voice = State()
    waiting_for_photo = State()
    waiting_for_content_plan_brief = State()
    waiting_for_examples = State()
    waiting_for_visual_request = State()
    waiting_for_free_analysis_text = State()
    waiting_for_analysis_goal = State()
    waiting_for_improvement_text = State()
    waiting_for_improvement_style = State()
    waiting_for_new_post_topic = State()
    waiting_for_new_post_goal = State()
    waiting_for_new_post_tone = State()
    waiting_for_cta_text = State()
    waiting_for_cta_type = State()
    waiting_for_ideas_topic = State()
    waiting_for_image_text = State()
    waiting_for_image_style = State()
    waiting_for_plan_niche = State()
    waiting_for_plan_goal = State()
    waiting_for_plan_period = State()
    waiting_for_manual_review_content = State()
